# Dockerfile for model_api.py
FROM python:3.9

WORKDIR /app

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "app.api.v1.model.model_api:app", "--host", "0.0.0.0", "--port", "8001"]

