# Dockerfile for model_api.py
FROM python:3.9

WORKDIR /app/api/v1

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . .

CMD ["uvicorn", "app.api.v1.model_api:app", "--host", "0.0.0.0", "--port", "8001"]
