version: '3.8'

services:
  wellnessapp:
    build:
      context: ./Wellnessapp
      dockerfile: Dockerfile
    container_name: wellnessapp
    ports:
      - "8000:8000"
    environment:
      - ENV_FILE=.env
    volumes:
      - ./Wellnessapp:/app

  wellnessmodel:
    build:
      context: ./Wellnessmodel
      dockerfile: Dockerfile-model
    container_name: wellnessmodel
    ports:
      - "8001:8001"
    environment:
      - ENV_FILE=.env
    volumes:
      - ./Wellnessmodel:/app
