version: '3'
services:
  main-service:
    image: python:3.9  
    container_name: main_service
    volumes:
      - ./:/app  
    working_dir: /app  
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000  
    ports:
      - "8000:8000" 

  model-service:
    image: python:3.9  
    container_name: model_service
    volumes:
      - ./:/app 
    working_dir: /app  
    command: uvicorn app.model_api:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8000"  
